In [1]:
# classification task 

In [1]:
import optuna

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\lenov\Downloads\winequality-red.csv")
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [4]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [5]:
x=df.drop(columns=['quality'])
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [6]:
y=df.quality
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [7]:
y=pd.get_dummies(y).values

In [8]:
y

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       ...,
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]], dtype=uint8)

In [9]:
from sklearn.model_selection import train_test_split
import xgboost as xgb
import numpy as np

In [16]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.20)


In [17]:
train_y=np.asarray(train_y)

In [18]:
train_y

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0],
       ...,
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]], dtype=uint8)

In [19]:
train_x=np.asarray(train_x)

In [20]:
train_x

array([[ 8.3 ,  0.76,  0.29, ...,  3.45,  0.68, 11.5 ],
       [10.2 ,  0.44,  0.58, ...,  3.29,  0.99, 12.  ],
       [ 7.1 ,  0.46,  0.14, ...,  3.36,  0.49, 10.7 ],
       ...,
       [ 8.  ,  0.38,  0.06, ...,  3.37,  0.52,  9.9 ],
       [ 9.5 ,  0.55,  0.66, ...,  3.17,  0.67,  9.6 ],
       [ 8.4 ,  0.62,  0.12, ...,  3.38,  0.89, 11.8 ]])

In [23]:
# xgb_classification=xgb.XGBClassifier()
# xgb_classification.fit(train_x,train_y,eval_set = [(test_x,test_y)])


In [10]:
def objective_classification(trial):
    train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.20)
    param={
        'tree_method': 'gpu_hist',
        'verbosity':3,
        'objective':"binary:logistics",
        'booster':trial.suggest_categorical('booster',['dart','gbtree','gblinear']),
        'lambda':trial.suggest_float('lambda',1e-4,1),
        'alpha':trial.suggest_float('alpha',1e-4,1),
        'subsample':trial.suggest_float('subsample',.1,.5),
        'colsample_bytree':trial.suggest_float('colsample_bytree',0.1,0.5)
        
    }
    
    if param['booster'] in ['gbtree','dart']:
        param['gamma']:trial.suggest_float('gamma',1e-3,4)
        param['eta']:trial.suggest_float('eta',0.001,5)
            
    
    
    xgb_classification=xgb.XGBClassifier(**param)
    xgb_classification.fit(train_x,train_y,eval_set = [(test_x,test_y)])
    pred=xgb_classification.predict(test_x)
    accuracy=xgb_classification.accuracy_score(test_x,test_y)
    
    
    return accuracy
            
            
            
            
            
            
            
            

In [11]:
xgb_classification_oputuna=optuna.create_study(direction='minimize')
xgb_classification_oputuna.optimize(objective_classification,n_trials=10)

[I 2023-01-05 18:33:54,243] A new study created in memory with name: no-name-15db09a3-8c6c-4d18-82e7-404326dda1ca
[W 2023-01-05 18:33:55,081] Trial 0 failed because of the following error: XGBoostError('[18:33:55] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-03de431ba26204c4d-1\\xgboost\\xgboost-ci-windows\\src\\objective\\objective.cc:26: Unknown objective function: `binary:logistics`\nObjective candidate: survival:aft\nObjective candidate: binary:hinge\nObjective candidate: multi:softmax\nObjective candidate: multi:softprob\nObjective candidate: rank:pairwise\nObjective candidate: rank:ndcg\nObjective candidate: rank:map\nObjective candidate: survival:cox\nObjective candidate: reg:gamma\nObjective candidate: reg:tweedie\nObjective candidate: reg:squarederror\nObjective candidate: reg:squaredlogerror\nObjective candidate: reg:logistic\nObjective candidate: binary:logistic\nObjective candidate: binary:logitraw\nObjective candidate: reg:linear\nObjective candid

[18:33:55] ======== Monitor (0): HostSketchContainer ========
[18:33:55] AllReduce: 0.000159s, 1 calls @ 159us

[18:33:55] MakeCuts: 0.000374s, 1 calls @ 374us



XGBoostError: [18:33:55] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-03de431ba26204c4d-1\xgboost\xgboost-ci-windows\src\objective\objective.cc:26: Unknown objective function: `binary:logistics`
Objective candidate: survival:aft
Objective candidate: binary:hinge
Objective candidate: multi:softmax
Objective candidate: multi:softprob
Objective candidate: rank:pairwise
Objective candidate: rank:ndcg
Objective candidate: rank:map
Objective candidate: survival:cox
Objective candidate: reg:gamma
Objective candidate: reg:tweedie
Objective candidate: reg:squarederror
Objective candidate: reg:squaredlogerror
Objective candidate: reg:logistic
Objective candidate: binary:logistic
Objective candidate: binary:logitraw
Objective candidate: reg:linear
Objective candidate: reg:absoluteerror
Objective candidate: reg:pseudohubererror
Objective candidate: count:poisson


In [12]:
param={
    'booster':'gblinear',
    'lambda':0.65797214,
    'alpha':0.466594,
    'subsample':0.2680125,
    'colsample_bytree':0.127745749
}

In [13]:
xgb_final_class=xgb.XGBClassifier(**param)

In [14]:
xgb_final_class

XGBClassifier(alpha=0.466594, base_score=None, booster='gblinear',
              callbacks=None, colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.127745749, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, lambda=0.65797214,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [29]:
xgb_final_class.fit(x=train_x,y=train_y)


TypeError: fit() got an unexpected keyword argument 'x'

In [31]:
train_x

array([[ 8.3 ,  0.76,  0.29, ...,  3.45,  0.68, 11.5 ],
       [10.2 ,  0.44,  0.58, ...,  3.29,  0.99, 12.  ],
       [ 7.1 ,  0.46,  0.14, ...,  3.36,  0.49, 10.7 ],
       ...,
       [ 8.  ,  0.38,  0.06, ...,  3.37,  0.52,  9.9 ],
       [ 9.5 ,  0.55,  0.66, ...,  3.17,  0.67,  9.6 ],
       [ 8.4 ,  0.62,  0.12, ...,  3.38,  0.89, 11.8 ]])

In [28]:
xgb_final_class.score(test_x,test_y)

NotFittedError: need to call fit or load_model beforehand